-- Create MEDICATION table
CREATE TABLE MEDICATION (
    MEDICATION_ID int PRIMARY KEY,
    MEDICATION_NAME varchar(100) NOT NULL
);

-- Create MEDICATION_CATEGORY table
CREATE TABLE MEDICATION_CATEGORY (
    MEDICATION_CATEGORY_ID int PRIMARY KEY,
    MEDICATION_CATEGORY_DESCRIPTION varchar(100) NOT NULL,
    MEDICATION_ID int NOT NULL,
    FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATION(MEDICATION_ID)
);

-- Create ACTIVE_INGREDIENT table
CREATE TABLE ACTIVE_INGREDIENT (
    ACTIVE_INGREDIENT_ID int PRIMARY KEY,
    ACTIVE_INGREDIENT_NAME varchar(100) NOT NULL
);

-- Create ACTIVE_INGREDIENT_CATEGORY table
CREATE TABLE ACTIVE_INGREDIENT_CATEGORY (
    ACTIVE_INGREDIENT_CATEGORY_ID int PRIMARY KEY,
    ACTIVE_INGREDIENT_CATEGORY_DESCRIPTION varchar(100) NOT NULL,
    ACTIVE_INGREDIENT_ID int NOT NULL,
    FOREIGN KEY (ACTIVE_INGREDIENT_ID) REFERENCES ACTIVE_INGREDIENT(ACTIVE_INGREDIENT_ID)
);

-- Create MEDICATION_ACTIVE_INGREDIENT junction table
CREATE TABLE MEDICATION_ACTIVE_INGREDIENT (
    MEDICATION_ACTIVE_INGREDIENT_ID int PRIMARY KEY,
    MEDICATION_ID int NOT NULL,
    ACTIVE_INGREDIENT_ID int NOT NULL,
    FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATION(MEDICATION_ID),
    FOREIGN KEY (ACTIVE_INGREDIENT_ID) REFERENCES ACTIVE_INGREDIENT(ACTIVE_INGREDIENT_ID)
);